server {
    listen 80;
    server_name dailsmart.in www.dailsmart.in;

    # Redirect HTTP to HTTPS (You can enable this once you have SSL certs)
    # return 301 https://$host$request_uri;

    location / {
        proxy_pass http://ui:3010;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name api.dailsmart.in;

    # Redirect HTTP to HTTPS (You can enable this once you have SSL certs)
    # return 301 https://$host$request_uri;

    location / {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
